### ISSUE TITLE
Can't load emoji cog.

### ISSUE THREAD

**Issue by Brandjuh** [Stonedestroyer/Stone-Cogs#1]
Thanks, for making the cog, I tried to ping you in the red server but could not find you.

I cannot load the cog, the following error is posted.

`Exception during loading of cog
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/redbot/core/core_commands.py", line 114, in _load
    await bot.load_extension(spec)
  File "/root/.local/lib/python3.8/site-packages/redbot/core/bot.py", line 801, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/emoji/__init__.py", line 1, in <module>
    from .emoji import Emoji
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/emoji/emoji.py", line 8
    __VERSION__ = 1.0.1
                     ^
SyntaxError: invalid syntax`

**Comment by Stonedestroyer** [comment]
This should be fixed now.
